### ISSUE TITLE
Opstellen Style Guide voor de website

### ISSUE THREAD

**Issue by patrickreijnen** [NLUUG/website#10]
Om een consistente opzet van de nieuwe NLUUG site te krijgen, is het wenselijk een style guide op te stellen, met daarin zaken als:

- Hoe ga je om met headers
- Hoe gaat je om met plaatjes
- Wanneer wel en wanneer niet een tabel gebruiken
- etc.

Dit zal een groei document zijn

**Comment by mboelen** [comment]
Eerste versie is gemaakt en staat live op de website. Zie /website/
