### ISSUE TITLE
Opzetten video specifieke xml-sitemap

### ISSUE THREAD

**Issue by patrickreijnen** [NLUUG/website#102]
Google Search wenst een video specifieke xml-sitemap. Kan op termijn zinvol zijn om daar aan toe te geven.

**Comment by mboelen** [comment]
Waar specifiek zie je dit? (ik neem aan in search console)

Ik denk als we alles op 1 plaats opslaan deze sitemap niet meer nodig is (of al onderdeel vormt van die software)

**Comment by mboelen** [comment]
Is dit issue nog relevant @patrickreijnen?

**Comment by patrickreijnen** [comment]
Geen idee... Willen we dit wel of niet?
Ik weet niet of dit wel of niet zinvol gaat zijn


⁣BlueMail voor Android downloaden ​

Op 11 feb. 2024 08:57, om 08:57, Michael Boelen ***@***.***> schreef:

**Comment by mboelen** [comment]
Dan sluiten we hem voor nu, aangezien content toch al vrij beschikbaar is voor de zoekmachines, inclusief opnames. Mochten we er later tegenaan lopen, dan kunnen we het alsnog bekijken.
