### ISSUE TITLE
Verbeterpuntjes leden.nluug.nl

### ISSUE THREAD

**Issue by mboelen** [NLUUG/website#109]
Weghalen van najaarsconferentie op leden.nluug.nl, aangezien dit niet relevant is voor ledendeel (en om te voorkomen dat na de conferentie er oud evenement staat).

De link 'home' laten verwijzen naar https://leden.nluug.nl/ ipv website. Als je inlogt en terugwilt naar hoofdpagina van ledendeel, dan is de home-link verwarrend.

**Comment by patrickreijnen** [comment]
Waar zie je Najaarsconferentie staan, anders dan op https://leden.nluug.nl/leden/admin/index.cgi die nodig is om aan te kunnen melden?

En NEE, home mag juist NIET verwijzen naar https://leden.nluug.nl/, hooguit naar https://leden.nluug.nl/leden/. Anders land je namelijk op de homepage van de oude site op de vps01. En dat willen we niet ... 

Misschien dat ik "home" vervang door "ledendeel" met verwijzing naar https://leden.nluug.nl/leden/

**Comment by mboelen** [comment]
Op https://leden.nluug.nl/ zelf. In plaats van najaarsconferentie een generiek kopje met een generieke link? Zoiets als "Aanmelden voor een evenement"

Verwijzen van home/ledendeel naar https://leden.nluug.nl/leden/ is inderdaad goede oplossing.

**Comment by mboelen** [comment]
Issue kan gesloten worden. Met in de toekomst een nieuw ledendeel, is dit deel van de oude pagina's wellicht toch al minder interessant om aan te passen.
