### ISSUE TITLE
Consistent gebruik van de term "buro" versus "ledenadministratie" binnen de site

### ISSUE THREAD

**Issue by patrickreijnen** [NLUUG/website#37]
"buro" en "ledenadministratie" worden door elkaar gebruikt binnen de site. Eén, consistent gebruikte term van maken, waarbij, mijns inziens, "ledenadministratie" de voorkeur verdient

**Comment by mboelen** [comment]
Besproken (Patrick en ik) en voor nu brengen we hierin geen wijzigingen aan.
