### ISSUE TITLE
Suggesties om naar te verwijzen (en terug te laten verwijzen) op de website.

### ISSUE THREAD

**Issue by synq** [NLUUG/website#4]
De NLUUG heeft een hele lijst met 'connecties' van organisaties en projecten die verwijzing waard zijn in het kader 'doel van de vereniging'. 

Dat zou op allemaal losse pagina's kunnen (wat op zich wel een goed idee is als je er als NLUUG bij wil zetten waarom je naar deze organsatie of dit project verwijst) of op een losse pagina. 

Ik stel voor om dit 'issue' te gebruiken om die suggesties te verzamelen.

**Comment by mboelen** [comment]
Een eerste opzet is gemaakt en verzameld met commit https://github.com/NLUUG/website/commit/6735925a325d945a85527125473b68565d1a1730

Omwille dat dit issue juist geen vergaarbak wordt, mag je aanvullende hackerspaces/initiatieven/communities delen via pull requests. De relevante data is te vinden binnen data/community: https://github.com/NLUUG/website/tree/main/data/community

Wij zullen ze dan mergen. Patrick en ik gaan nog even kijken hoe we deze pagina's goed onder kunnen brengen, zodat ze een goede plaats krijgen binnen de website. Voor nu sluit ik dit issue, zodat we de rest van de punten kunnen wegwerken.
