### ISSUE TITLE
Ondersteun light/dark-mode website

### ISSUE THREAD

**Issue by mboelen** [NLUUG/website#49]
Zie o.a. implementatie Github en [Mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

**Comment by patrickreijnen** [comment]
Is er een valide reden waarom we dit zouden moeten willen?

**Comment by mboelen** [comment]
Ja, omdat je de bezoeker die dark-mode gebruikt tegemoet komt. Vraag is alleen hoeveel moeite we er in moeten stoppen en of het wellicht al standaard werkt bij juiste opmaak van HTML.

**Comment by mboelen** [comment]
Ik kan het niet goed testen op mijn systeem, dus voor nu laten we dit achterwege zodat we andere zaken eerst kunnen oppakken.
