### ISSUE TITLE
Uitzoeken: willen we brotli-compressie ondersteunen?

### ISSUE THREAD

**Issue by mboelen** [NLUUG/website#52]

**Comment by patrickreijnen** [comment]
Gaat compressie daadwerkelijk nog iets toevoegen voor snelheid van onze toch al lean and mean site, of gaat het juist vertragend werken?

**Comment by mboelen** [comment]
Compressie hebben we al (gzip) en het scheelt zeker. Minder data over de lijn zal vooral op mobiele apparaten helpen, zeker als de verbinding traag of onstabiel is.

Het mooiste is om de bestanden te comprimeren voor eerste gebruik en direct van de disk te halen, zo is er minder rekenkracht nodig op het moment van het verzoek.

Brotli komt inderdaad niet standaard gecompileerd mee met nginx-package, maar is vaak als addon te installeren. De vraag is alleen of het de extra moeite en beheerlast waard is.

**Comment by mboelen** [comment]
Voor nu ga we dit niet doen, aangezien andere zaken meer prioriteit hebben. We kunnen later alsnog bekijken of het de moeite waard is.
