### ISSUE TITLE
Breedte van de footer

### ISSUE THREAD

**Issue by RonnyLam** [NLUUG/website#53]
Ik vindt de breedte van de blauwe footer niet passen bij de rest van de pagina. Kan deze breedte gelijk getrokken worden aan de rest?

**Comment by mboelen** [comment]
Toevallig hebben Patrick en ik het er gisteren over gehad en er zijn twee opties:

1. Header/footer beiden over de gehele breedte
2. Header/footer beiden net zo groot als de content

Bij deze optie 2 toegepast. Wellicht dat we optie 1 later nog bekijken, maar voor nu zijn header/content/footer even breed.
