### ISSUE TITLE
Weglaten "Help mee" kop in de footer voor bepaalde pagina's

### ISSUE THREAD

**Issue by patrickreijnen** [NLUUG/website#56]
Op bepaalde pagina's zoals https://www3.nluug.nl/tags/website/ staat in de footer een loze kop "Help mee" zonder verder inhoud eronder.
Kan deze weg gelaten worden?

**Comment by mboelen** [comment]
Voor dit soort overzichtspagina's (waar geen tekst is) is er nu een alternatieve knop gemaakt met de tekst "Deel feedback" en een verwijzing naar de feedback-pagina.
