### ISSUE TITLE
Oppakken: opmaak van Talks en Sprekers

### ISSUE THREAD

**Issue by patrickreijnen** [NLUUG/website#58]
Opmaak van Talks en Sprekers moet nog uitgewerkt worden

**Comment by mboelen** [comment]
Een groot deel daarvan is inmiddels gedaan. Ontbreekt er nog iets?

**Comment by mboelen** [comment]
Voornaamste zit er nu in (programma, lezingen, persoonlijke pagina's, talks gekoppeld aan persoon, schema.org Person). Dus dit issue beschouw ik als afgerond. Verbeteringen kunnen als nieuw issue aangemaakt worden.
