### ISSUE TITLE
Projecten pagina niet meer gekoppeld binnen de site

### ISSUE THREAD

**Issue by patrickreijnen** [NLUUG/website#75]
De projecten pagina is momenteel allee nog te vinden via de sitemap. Hij is verdwenen van de hoofdpagina waar hij oorspronkelijk te gelinked was

**Comment by mboelen** [comment]
Die link is er nog steeds.

`Op de pagina **Projecten** beschrijven we deze en andere projecten. Meehelpen? Contacteer een actief projectlid voor meer informatie.`

**Comment by patrickreijnen** [comment]
Ik zal mijn bril weer eens gaan opzetten ....
