### ISSUE TITLE
Toevoegen Jan Christiaan van Winkel en Mike Hulsman aan FTP-team

### ISSUE THREAD

**Issue by mboelen** [NLUUG/website#77]

**Comment by patrickreijnen** [comment]
Nog foto's van personen toevoegen

**Comment by mboelen** [comment]
Foto's toegevoegd en aan organisatie gehangen. Kun jij dubbelcheck doen om te zien of alles goed staat?

**Comment by patrickreijnen** [comment]
Compleet en correct
