### ISSUE TITLE
Alle pagina's voorzien van Header Meta data

### ISSUE THREAD

**Issue by patrickreijnen** [NLUUG/website#8]
Op de huidige site heeft alleen de hoofdpagina uitgebreide meta data in de header.

Alle pagina's dienen, pagina specifieke, meta data te krijgen

**Comment by mboelen** [comment]
Als er een specifieke header ontbreekt, dan pakken we die los op. Voor nu zitten er de belangrijkste headers in. Dit is o.a. getest met performance testing tools (gtmetrix, pingdom, pagespeed). Ook de benodigde tags voor social media zijn aanwezig.

Dit issue kan daarom gesloten worden.
