### ISSUE TITLE
website feedback

### ISSUE THREAD

**Issue by kwoot** [NLUUG/website#84]
Hoi!

Ik ben ongetwijfeld te snel met mijn feedback. Sorry daarvoor.

Congrats voor de switch naar PReTalx. Dat is awesome software.

Een paar puntjes (ik hoop dat ik het goed verwoord):

- Waar https://nluug.nl/evenementen/nluug/najaarsconferentie-2023/ de indruk wekt dat je je al kunt inschrijven voor de njconf, dat luke mij in ieder geval niet.
- Oude userid wachtwoord, werkt niet in pretalx omgeving
- De pretalx login pagina is het onduidelijk dat je eerst een talk moet indienen voor je een (apart) account krijgt.

Succes met de verdere klus!

Jeroen

**Comment by mboelen** [comment]
Hey Jeroen.

Bedankt voor je feedback. Nooit te vroeg :-)

1) Inschrijving staat nog niet open. Ik zal dit aan buro vragen om te doen.
2) Klopt, accounts gaan niet mee over aangezien het een nieuw systeem is.
3) Als het goed is kun je eerst je account aanmaken: klik op het event, dan rechtsboven op login, dan aan rechterzijde kun je account registreren.

Daarmee puntje 2 en 3 opgelost?
