### ISSUE TITLE
Bij elke conferentie alle sponsoren met logo + link weergeven

### ISSUE THREAD

**Issue by patrickreijnen** [NLUUG/website#88]
In de huidige opzet staat eigen altijd alleen de sponsor van de borrel op de pagina van een conferentie, omdat dit in het programma zit. De overige sponsoren van dezelfde conferentie zijn niet meer terug te vinden. Eigenlijk niet zo netjes,

Daarnaast is het misschien wel netjes om de sponsoren met logo en link op te nemen bij de de conferenties

**Comment by mboelen** [comment]
Inderdaad, dat is ook mijn gedachte erbij. Hiervoor moeten we een generieke data-structuur aanmaken met de sponsoren, zodat we ze kunnen koppelen aan de betreffende conferenties. Dat is nog een actie die loopt.

**Comment by mboelen** [comment]
Functionaliteit is inmiddels ingebouwd en sponsoren kunnen nu gekoppeld worden aan een evenement. Dus bij deze dit punt ook afgerond.
