### ISSUE TITLE
Controleren of alle moderne headers aanwezig zijn.

### ISSUE THREAD

**Issue by mboelen** [NLUUG/website#91]
Controleren of onderstaande headers aanwezig/afwezig zijn. Let op: sommigen zijn mogen afwezig blijven, zoals X-Powered-By.

Zinvolle bron is https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

- X-XSS-Protection
- Expect-CT - ✔️ **Niet nodig** (Is verdwenen als header / gaat op korte termijn verdwijnen)
- Access-Control-Allow-Origin
- Access-Control-Allow-Methods
- Access-Control-Allow-Headers
- X-Content-Security-Policy - ✔️ **Niet nodig, we hebben al CSP**
- X-Content-Type-Options
- X-Frame-Options - ✔️ **Aanwezig** (DENY)
- X-Permitted-Cross-Domain-Policies
- X-Powered-By - ✔️ **Afwezig** (dat is goed)
- Content-Security-Policy - ✔️Aanwezig
- Referrer-Policy - ✔️ **Aanwezig** (same-origin)
- HTTP Strict Transport Security / HSTS - ✔️ **Aanwezig**
- Content-Security-Policy ✔️ **Aanwezig** (inline stylesheet is wel nodig)
- Clear-Site-Data - ❌ Deze header zou mooi passen binnen een uitlog-link.
- Cross-Origin-Embedder-Policy-Report-Only
- Cross-Origin-Opener-Policy-Report-Only
- Cross-Origin-Embedder-Policy
- Cross-Origin-Opener-Policy
- _Cross-Origin-Resource-Policy_
- Permissions-Policy - ✔️ **Aanwezig**
- Strict-dynamic

**Comment by patrickreijnen** [comment]
HTTP Strict Transport Security / HSTS --> Check (internet.nl)
Referrer-Policy --> Check (internet.nl)
Content-Security-Policy --> Check (internet.nl) --> MET BEVINDINGEN
X-Content-Type-Options --> Check (internet.nl)

**Comment by mboelen** [comment]
Lijkt dat we aardig compleet zijn met wat we hebben gedaan. Zeker met statische output is er weinig risico verder.
