### ISSUE TITLE
Verbeteren tabel opmaak op Commissies pagina

### ISSUE THREAD

**Issue by patrickreijnen** [NLUUG/website#92]
De tabel opmaak op https://nluug.nl/organisatie/commissies/ is nogal "op elkaar gepropt". 
Een wat ruimere opzet van de tabel, in iedere geval in de breedte op de pagina, maakt eea leesbaarder.

**Comment by mboelen** [comment]
Opgelost door tabel weg te halen en pagina te versimpelen. Relevante commit https://github.com/NLUUG/website/commit/767a6970e3f43e09e47a0c8e2d64c592abb414bb
